#!/bin/sh

DAEMON="p1_edge_daemon"
EXEC="/usr/bin/$DAEMON"
PIDFILE="/var/run/$DAEMON.pid"

start() {
    echo -n "Starting $DAEMON: "
    start-stop-daemon -S -b -m -p $PIDFILE -x $EXEC
    [ $? -eq 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    echo -n "Stopping $DAEMON: "
    start-stop-daemon -K -p $PIDFILE
    [ $? -eq 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
